### ISSUE TITLE
AeroRust's "Are we in space yet?" catalogue and `no_std` support

### ISSUE THREAD

**Issue by elpiel** [neuromorphicsystems/sgp4#7]
Hello,
I'm the community manager of the AeroRust community and while researching different crates for orbital determination and propagation I landed on your project.

We have an ongoing effort to create a catalogue of crates related to aerospace.
I'd love to see `sgp4` added to the `Are we in space yet?` catalogue - https://aerorust.org/catalogue/.
You can find `sgp4` and other crates for addition to the website here - https://github.com/AeroRust/AeroRust.github.io/issues/6
The categories are still a Work in progress and any additions/alterations are welcome.

On another note, I would love to see whether `no_std` is possible for the `sgp4` crate at this stage and if all dependencies are needed to minimise the crate size for use in embedded.

**Comment by aMarcireau** [comment]
Hello,

That sounds like an exciting project! Do I need to do anything to add SGP4 to the `Are we in space yet?` catalogue?

`no_std` is possible in principle, but challenging because SGP4 uses trigonometric functions. These functions depend on the host OS for the moment. The following issue tracks ongoing efforts and suggested workarounds: https://github.com/rust-lang/rfcs/issues/2505. However, the workarounds are platform-dependent.

**Comment by elpiel** [comment]
> Hello,
> 
> That sounds like an exciting project! Do I need to do anything to add SGP4 to the `Are we in space yet?` catalogue?
> 
> `no_std` is possible in principle, but challenging because SGP4 uses trigonometric functions. These functions depend on the host OS for the moment. The following issue tracks ongoing efforts and suggested workarounds: [rust-lang/rfcs#2505](https://github.com/rust-lang/rfcs/issues/2505). However, the workarounds are platform-dependent.

### Catalogue addition
To add the crate you must update the `scraper/config.toml` file and define the categories in which `sgp4` is part of ( astrodynamics I suppose). More details can be found in the issue - https://github.com/AeroRust/AeroRust.github.io/issues/6

### `no_std`
In the `nmea` crate we've used the `num` crate to add support for f32/f64 functions that are not included in `core` and it does support `no_std` - https://docs.rs/num/latest/num/trait.Float.html
You can rely only on the `num-traits` in this scenario.


https://github.com/AeroRust/nmea/blob/b73418af5bb61400e91c27bb3aa6103573fc182d/src/sentences/utils.rs#L14-L16

https://github.com/AeroRust/nmea/blob/b73418af5bb61400e91c27bb3aa6103573fc182d/src/sentences/utils.rs#L44

**Comment by elpiel** [comment]
Thanks again for adding this amazing crate to the list.
