### ISSUE TITLE
Add the WAPM library links to the documentation

### ISSUE THREAD

**Issue by dynamite-bud** [neuromorphicsystems/sgp4#9]
I have ported to library to WebAssembly and generated bindings for `python` and `javascript`.
sgp4 ported [repository](https://github.com/wasmerio/sgp4)

Hosted Bindings on [WAPM](https://wapm.io/dynamite-bud/sgp4)

Now the library can be used from `python` and `javascript`.

Need to add this to the documentation.

**Comment by aMarcireau** [comment]
Hi @dynamite-bud Thanks, this looks incredibly useful! Would you prefer a link to your Github repository or the WAPM page?

**Comment by dynamite-bud** [comment]
https://wapm.io/dynamite-bud/sgp4
https://github.com/wasmerio/sgp4

**Comment by dynamite-bud** [comment]
GitHub repository would be fine, as we have the WAPM packages there.
